# Generated by Django 4.0.2 on 2022-02-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('docket_no', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
