# Generated by Django 3.1 on 2022-03-04 17:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('email', models.EmailField(default='sendhwamadhurcourierservices@gmail.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('docket_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('date_generate', models.DateField(default=datetime.datetime.now)),
                ('bill_date_from', models.DateField(default=datetime.datetime.now)),
                ('bill_date_to', models.DateField(default=datetime.datetime.now)),
                ('price', models.CharField(max_length=70)),
                ('billof', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
            ],
        ),
    ]
