# Generated by Django 4.0.2 on 2022-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='docket_no',
            field=models.CharField(max_length=20),
        ),
    ]
