# Generated by Django 3.1 on 2022-03-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(blank=True, default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
            ],
        ),
    ]
