# Generated by Django 4.0.2 on 2022-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_docket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
