# Generated by Django 3.1 on 2022-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sno',
            field=models.IntegerField(default=0),
        ),
    ]
