# Generated by Django 3.1 on 2022-03-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='s_no',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Serial_number',
        ),
    ]
