# Generated by Django 4.0.2 on 2022-02-21 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 21, 16, 16, 2, 466113)),
        ),
    ]
