# Generated by Django 4.0.2 on 2022-02-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='data',
        ),
        migrations.AddField(
            model_name='bookings',
            name='data',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
