# Generated by Django 4.0.2 on 2022-02-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_bookings_data_bookings_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='data',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
