# Generated by Django 4.0.2 on 2022-02-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_bookings_data_alter_bookings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.bookings'),
            preserve_default=False,
        ),
    ]
