# Generated by Django 3.1 on 2022-02-27 12:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField(unique=True)),
                ('date_generate', models.DateField(default=datetime.datetime.now)),
                ('bill_date_range', models.CharField(max_length=70)),
                ('bill_cnote_range', models.CharField(max_length=70)),
                ('price', models.CharField(max_length=70)),
                ('billof', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.bookings')),
            ],
        ),
    ]
