# Generated by Django 3.1 on 2022-02-27 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220227_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_date_range',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date_from',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date_to',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
