# Generated by Django 3.1 on 2022-02-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220227_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_cnote_range',
        ),
    ]
