# Generated by Django 3.1 on 2022-03-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20220227_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='email',
            field=models.EmailField(default='sendhwamadhurcourierservices@gmail.com', max_length=100),
        ),
    ]
